project_id = "dbjbhemmtdkzulsxfvmi"

[functions.file-scan]
verify_jwt = false

[functions.operations-dispatch]
verify_jwt = false

[functions.billing]
verify_jwt = false

[functions.integration-admin]
verify_jwt = false

[functions.integration-dispatch]
verify_jwt = false

[functions.notification-dispatch]
verify_jwt = false

[functions.operations-health]
verify_jwt = false

[functions.platform-admin]
verify_jwt = false
