import { PDFDocument, rgb, StandardFonts } from "pdf-lib";
import { corsHeaders, json, preflight, requirePost } from "../_shared/http.ts";
import { requireUser } from "../_shared/supabase.ts";

type ExportInput = { from?: string; to?: string };

Deno.serve(async (request) => {
  const early = preflight(request) ?? requirePost(request);
  if (early) return early;
  try {
    const { client, user } = await requireUser(request);
    const input = (await request.json()) as ExportInput;
    const from = input.from
      ? new Date(input.from)
      : new Date(Date.now() - 30 * 86400000);
    const to = input.to ? new Date(input.to) : new Date();
    if (
      !Number.isFinite(from.getTime()) ||
      !Number.isFinite(to.getTime()) ||
      to < from ||
      to.getTime() - from.getTime() > 366 * 86400000
    ) {
      return json(request, { error: "invalid_date_range" }, 400);
    }

    const [
      { data: context },
      organizations,
      locations,
      temperatures,
      outOfRangeTemperatures,
      checks,
      audits,
      recalls,
      training,
      fitness,
      equipment,
    ] = await Promise.all([
      client.rpc("get_my_context"),
      client
        .from("temperature_logs")
        .select("location,reading,status,logged_at", { count: "exact" })
        .gte("logged_at", from.toISOString())
        .lte("logged_at", to.toISOString())
        .limit(1000),
      client
        .from("temperature_logs")
        .select("id", { count: "exact", head: true })
        .eq("status", "out_of_range")
        .gte("logged_at", from.toISOString())
        .lte("logged_at", to.toISOString()),
      client
        .from("checks")
        .select("kind,title,status,completed_at", { count: "exact" })
        .eq("status", "completed")
        .gte("created_at", from.toISOString())
        .lte("created_at", to.toISOString())
        .limit(1000),
      client
        .from("audits")
        .select("title,audit_type,score,status,performed_at", {
          count: "exact",
        })
        .gte("performed_at", from.toISOString())
        .lte("performed_at", to.toISOString())
        .limit(300),
      client
        .from("recalls")
        .select("product,batch,severity,status,initiated_at", {
          count: "exact",
        })
        .neq("status", "closed")
        .gte("initiated_at", from.toISOString())
        .lte("initiated_at", to.toISOString())
        .limit(300),
      client
        .from("training_records")
        .select("progress,score,completed_at,verified_at", { count: "exact" })
        .not("verified_at", "is", null)
        .gte("created_at", from.toISOString())
        .lte("created_at", to.toISOString())
        .limit(1000),
      client
        .from("health_register")
        .select("id", { count: "exact", head: true })
        .gte("created_at", from.toISOString())
        .lte("created_at", to.toISOString()),
      client
        .from("asset_events")
        .select("event_type,outcome,title,notes,recorded_by_name,recorded_at", {
          count: "exact",
        })
        .gte("recorded_at", from.toISOString())
        .lte("recorded_at", to.toISOString())
        .limit(1000),
    ]);
    for (
      const result of [
        temperatures,
        outOfRangeTemperatures,
        checks,
        audits,
        recalls,
        training,
        fitness,
        equipment,
      ]
    ) {
      if (result.error) throw result.error;
    }

    const { error: auditError } = await client.rpc("record_evidence_export", {
      p_from: from.toISOString().slice(0, 10),
      p_to: to.toISOString().slice(0, 10),
    });
    if (auditError) throw auditError;

    const ctx =
      context && typeof context === "object" && !Array.isArray(context)
        ? (context as Record<string, unknown>)
        : {};
    const ascii = (value: unknown) =>
      String(value ?? "")
        .normalize("NFKD")
        .replace(/[^\x20-\x7E]/g, "?")
        .slice(0, 150);
    const lines: string[] = [
      `Organization: ${String(ctx.organization_name ?? "Haccora workspace")}`,
      `Location: ${String(ctx.location_name ?? "All granted locations")}`,
      `Period: ${from.toISOString().slice(0, 10)} to ${
        to.toISOString().slice(0, 10)
      }`,
      `Generated by: ${user.email ?? user.id}`,
      "",
      `Temperature records: ${temperatures.count ?? 0}`,
      `Out-of-range temperatures: ${outOfRangeTemperatures.count ?? 0}`,
      `Completed checks: ${checks.count ?? 0}`,
      `Audits: ${audits.count ?? 0}`,
      `Open recalls: ${recalls.count ?? 0}`,
      `Verified training records: ${training.count ?? 0}`,
      `Fitness-to-work records visible to this user: ${fitness.count ?? 0}`,
      `Equipment history records: ${equipment.count ?? 0}`,
      "Detailed sections include bounded record samples; totals above are exact for the selected period.",
      "",
      "TEMPERATURE RECORDS",
      ...(temperatures.data ?? [])
        .slice(0, 250)
        .map(
          (row) =>
            `${row.logged_at} | ${ascii(row.location)} | ${row.reading} C | ${
              ascii(row.status)
            }`,
        ),
      "",
      "COMPLETED CHECKS",
      ...(checks.data ?? [])
        .slice(0, 250)
        .map(
          (row) =>
            `${row.completed_at ?? "not completed"} | ${ascii(row.kind)} | ${
              ascii(
                row.title,
              )
            } | ${ascii(row.status)}`,
        ),
      "",
      "AUDITS",
      ...(audits.data ?? [])
        .slice(0, 150)
        .map(
          (row) =>
            `${row.performed_at} | ${ascii(row.audit_type)} | ${
              ascii(
                row.title,
              )
            } | score ${row.score ?? "-"} | ${ascii(row.status)}`,
        ),
      "",
      "RECALLS",
      ...(recalls.data ?? [])
        .slice(0, 150)
        .map(
          (row) =>
            `${row.initiated_at} | ${ascii(row.product)} | batch ${
              ascii(
                row.batch,
              )
            } | ${ascii(row.severity)} | ${ascii(row.status)}`,
        ),
      "",
      "TRAINING",
      ...(training.data ?? [])
        .slice(0, 250)
        .map(
          (row) =>
            `${
              row.completed_at ?? "not completed"
            } | progress ${row.progress}% | score ${
              row.score ?? "-"
            } | verified ${row.verified_at ?? "no"}`,
        ),
      "",
      "EQUIPMENT, MAINTENANCE AND CHECKS",
      ...(equipment.data ?? [])
        .slice(0, 250)
        .map(
          (row) =>
            `${row.recorded_at} | ${ascii(row.event_type)} | ${
              ascii(row.outcome)
            } | ${ascii(row.title)} | ${ascii(row.recorded_by_name)} | ${
              ascii(row.notes)
            }`,
        ),
      "",
      "Generated from tenant-scoped data. Export creation is recorded in the immutable audit chain.",
    ];

    const pdf = await PDFDocument.create();
    const font = await pdf.embedFont(StandardFonts.Helvetica);
    const bold = await pdf.embedFont(StandardFonts.HelveticaBold);
    let page = pdf.addPage([595.28, 841.89]);
    let pageNumber = 1;
    let y = 755;
    const drawHeader = () => {
      page.drawText("Haccora inspection evidence pack", {
        x: 48,
        y: 790,
        size: 18,
        font: bold,
        color: rgb(0.08, 0.08, 0.08),
      });
      page.drawText(`Page ${pageNumber}`, { x: 500, y: 794, size: 8, font });
    };
    drawHeader();
    for (const line of lines) {
      if (y < 48) {
        page = pdf.addPage([595.28, 841.89]);
        pageNumber += 1;
        y = 755;
        drawHeader();
      }
      page.drawText(ascii(line).slice(0, 105), {
        x: 48,
        y,
        size: 9,
        font: /^[A-Z ]+$/.test(line) ? bold : font,
        color: rgb(0.15, 0.15, 0.15),
      });
      y -= 14;
    }
    const bytes = await pdf.save();
    const body = new Uint8Array(bytes).buffer;
    return new Response(body, {
      headers: {
        ...corsHeaders(request),
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="haccora-evidence-${
          to
            .toISOString()
            .slice(0, 10)
        }.pdf"`,
        "Cache-Control": "no-store",
        "X-Content-Type-Options": "nosniff",
      },
    });
  } catch (error) {
    console.error(error);
    return json(
      request,
      {
        error: error instanceof Error && error.message === "Unauthorized"
          ? "unauthorized"
          : "export_failed",
      },
      error instanceof Error && error.message === "Unauthorized" ? 401 : 500,
    );
  }
});
