ALTER TABLE public.haccp_flow_runs
  ADD COLUMN IF NOT EXISTS photo_path TEXT,
  ADD COLUMN IF NOT EXISTS geo_lat NUMERIC,
  ADD COLUMN IF NOT EXISTS geo_lng NUMERIC,
  ADD COLUMN IF NOT EXISTS geo_accuracy NUMERIC,
  ADD COLUMN IF NOT EXISTS captured_at TIMESTAMPTZ;